# Seastar-RS Configuration Example (TOML)

[app]
name = "seastar-rs-demo"
version = "0.1.0"
environment = "production"
instance_id = "prod-001"

[reactor]
task_queue_size = 4096
io_polling_timeout_ms = 50
enable_io_uring = true
max_io_operations = 2048

[smp]
num_shards = 8
pin_threads = true
message_queue_size = 4096
enable_work_stealing = false

[database]
url = "postgres://postgres:password@localhost:5432/seastar_prod"
max_connections = 50
min_connections = 5
connect_timeout_secs = 30
query_timeout_secs = 30
max_lifetime_secs = 3600
idle_timeout_secs = 600
enable_logging = false

[metrics]
enabled = true
export_interval_secs = 30

[metrics.http_server]
bind = "0.0.0.0"
port = 8080
enable_dashboard = true

[metrics.prometheus]
registry = "seastar-prod"
enable_push_gateway = true
push_gateway_url = "http://prometheus-gateway:9091"

[metrics.file_export]
directory = "/var/log/seastar-rs/metrics"
format = "json"
rotation_interval_secs = 3600
max_files = 48

[logging]
level = "info"
format = "json"
colored = false
structured = true

[logging.file]
path = "/var/log/seastar-rs/app.log"
max_size_mb = 500
max_files = 50
compress = true

[tls]
cert_file = "/etc/ssl/certs/seastar-prod.pem"
key_file = "/etc/ssl/private/seastar-prod.key"
ca_file = "/etc/ssl/ca-bundle.pem"
require_client_cert = true
min_version = "1.3"
cipher_suites = ["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256"]

[websocket]
max_message_size = 2097152  # 2MB
max_frame_size = 131072     # 128KB
ping_interval_secs = 30
connection_timeout_secs = 60
max_connections = 5000